config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :forgotmails
  
  root 'forgotmails#index'

end

app/models/forgotmail.rb
class Forgotmail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forgotmails_controller.rb
class ForgotmailsController < ApplicationController
  before_action :set_forgotmail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /forgotmails
  # GET /forgotmails.json
  def index
    @forgotmails = Forgotmail.all
  end

  # GET /forgotmails/1
  # GET /forgotmails/1.json
  def show
  end

  # GET /forgotmails/new
  def new
    @forgotmail = Forgotmail.new
  end

  # GET /forgotmails/1/edit
  def edit
  end

  # POST /forgotmails
  # POST /forgotmails.json
  def create
    @user = current_user;
    @forgotmail = Forgotmail.new(forgotmail_params)
    
    Usermailer.welcome_email(@user, @forgotmail.sender, @forgotmail.reciever, @forgotmail.title, @forgotmail.content).deliver_now

    respond_to do |format|
      if @forgotmail.save
        format.html { redirect_to @forgotmail, notice: 'Forgotmail was successfully created.' }
        format.json { render :show, status: :created, location: @forgotmail }
      else
        format.html { render :new }
        format.json { render json: @forgotmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forgotmails/1
  # PATCH/PUT /forgotmails/1.json
  def update
    respond_to do |format|
      if @forgotmail.update(forgotmail_params)
        format.html { redirect_to @forgotmail, notice: 'Forgotmail was successfully updated.' }
        format.json { render :show, status: :ok, location: @forgotmail }
      else
        format.html { render :edit }
        format.json { render json: @forgotmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forgotmails/1
  # DELETE /forgotmails/1.json
  def destroy
    @forgotmail.destroy
    respond_to do |format|
      format.html { redirect_to forgotmails_url, notice: 'Forgotmail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forgotmail
      @forgotmail = Forgotmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forgotmail_params
      params.require(:forgotmail).permit(:sender, :reciever, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forgotmails_helper.rb
module ForgotmailsHelper
end

app/views/forgotmails/_form.html.erb
<%= form_for(@forgotmail) do |f| %>
  <% if @forgotmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forgotmail.errors.count, "error") %> prohibited this forgotmail from being saved:</h2>

      <ul>
      <% @forgotmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="email-sender"%>
    <%= f.label :sender, "보내는 이"%>
    <%= f.text_field :sender, class: "form-control form-control-sm", id: "lgFormGroupInput", placeholder: "you@example.com" %>
  </div>
  
  <div class="email-reciever"%>
    <%= f.label :reciever, "받는 이"%>
    <%= f.text_field :reciever, class: "form-control form-control-lg", id:"lgFormGroupInput", placeholder: "who@example.com" %>
  </div>
  
  <div class="email-title"%>
    <%= f.label :title, "이메일 제목"%>
    <%= f.text_field :title %>
  </div>
  
  <div class="email-content"%>
    <%= f.label :content, "이메일 내용"%>
    <%= f.text_area :content, size: "60x12" %>
  </div>

  <div class="actions">
    <%= f.submit "메일전송", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/forgotmails/edit.html.erb
<h1>Editing Forgotmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @forgotmail %> |
<%= link_to 'Back', forgotmails_path %>

app/views/forgotmails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forgotmails</h1>

<h4>보낸 메일함</h4>
<table>
  <thead>
    <tr>
      <th>받는 이</th>
      <th>보내는 이</th>
      <th>제목</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @forgotmails.each do |forgotmail| %>
      <tr>
        <td><%=forgotmail.reciever%></td>
        <td><%=forgotmail.sender%></td>
        <td><%=forgotmail.title%></td>
        <td><%= link_to 'Show', forgotmail %></td>
        <td><%= link_to 'Edit', edit_forgotmail_path(forgotmail) %></td>
        <td><%= link_to 'Destroy', forgotmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '새로운 메일 보내기', new_forgotmail_path, class:  "btn btn-primary" %>

app/views/forgotmails/new.html.erb
<h1>New Forgotmail</h1>

<%= render 'form' %>

<%= link_to 'Back', forgotmails_path, class:  "btn btn-primary"  %>

app/views/forgotmails/show.html.erb
<p id="notice"><%= notice %></p>

보내는 이 : <%=@forgotmail.sender%> <br>
받는 이 : <%=@forgotmail.reciever%> <br>
제목 : <%=@forgotmail.title%> <br>
내용 : <%=@forgotmail.content%> <br>

<%= link_to 'Edit', edit_forgotmail_path(@forgotmail), class:  "btn btn-primary"  %> |
<%= link_to 'Back', forgotmails_path,  class:  "btn btn-primary"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
  
  <!-- 합쳐지고 최소화된 최신 CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- 부가적인 테마 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>


</head>

<body>

<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Rails<i>Cafe</i></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %><li><br><strong><%= current_user.email %></strong>.</li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      
      </div>
    </div>



    <div class="container">
      <br><br><br><br><br><br>

      <%= yield %>
    </div>

</body>
</html>